export const TOGGLE_UNIVERSAL_MODAL = 'TOGGLE_UNIVERSAL_MODAL';
export const SET_FIREBASE_AUTH = 'SET_FIREBASE_AUTH';
export const SIGN_OUT = 'SIGN_OUT';
export const ZIP_CODE_OPTIONS = 'SET_ZIP_CODE_OPTIONS';
export const COMMUNITIES = 'LIST_OF_COMMUNITIES';
export const ACTIVE_COMMUNITY = 'ACTIVE_COMMUNITY';
